# Generated by Django 4.2.4 on 2023-08-31 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppinglistitem',
            name='bought',
            field=models.BooleanField(default=False),
        ),
    ]
