# Generated by Django 3.2.21 on 2023-09-13 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0004_cleaninglistitem_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='cleaninglistitem',
            name='frequency',
            field=models.CharField(blank=True, choices=[('D', 'Daily'), ('W', 'Weekly'), ('M', 'Monthly')], max_length=1),
        ),
    ]
